// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Header.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    NAnchor: typeof import('naive-ui')['NAnchor']
    NB: typeof import('naive-ui')['NB']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  }
}

export { }
