// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Header.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    NAnchor: typeof import('naive-ui')['NAnchor']
    NAuto: typeof import('naive-ui')['NAuto']
    'NAuto-': typeof import('naive-ui')['NAuto-']
    NAutoC: typeof import('naive-ui')['NAutoC']
    NAutoCo: typeof import('naive-ui')['NAutoCo']
    NAutoComplete: typeof import('naive-ui')['NAutoComplete']
    NB: typeof import('naive-ui')['NB']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NFormItemRow: typeof import('naive-ui')['NFormItemRow']
    NInput: typeof import('naive-ui')['NInput']
    NL: typeof import('naive-ui')['NL']
    NLa: typeof import('naive-ui')['NLa']
    NLay: typeof import('naive-ui')['NLay']
    NLayo: typeof import('naive-ui')['NLayo']
    NLayou: typeof import('naive-ui')['NLayou']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('./src/components/NLoadingBarProvider.vue')['default']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    RegisterIcons: typeof import('./components/Sider/RegisterIcons.vue')['default']
    Sider: typeof import('./components/Sider/Sider.vue')['default']
    ToggleTheme: typeof import('./components/ToggleTheme.vue')['default']
  }
}

export { }
